"""initial

Revision ID: 4b3514badafe
Revises: 
Create Date: 2026-05-29 02:32:33.691253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b3514badafe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_profile_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dog_profile_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media_records', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('good_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('good_with_cats', sa.Boolean(), nullable=True),
    sa.Column('good_with_kids', sa.Boolean(), nullable=True),
    sa.Column('good_with_other_animals', sa.Boolean(), nullable=True),
    sa.Column('house_trained', sa.Boolean(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('requires_fenced_yard', sa.Boolean(), nullable=True),
    sa.Column('vaccinated', sa.Boolean(), nullable=True),
    sa.Column('adoption_fee', sa.Float(), nullable=True),
    sa.Column('adoption_fee_waived', sa.Boolean(), nullable=True),
    sa.Column('shelter_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dog_profile_history_profile_id', 'dog_profile_history', ['dog_profile_id'], unique=False)
    op.create_table('dog_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=True),
    sa.Column('microchip_id', sa.String(length=255), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('match_label', sa.String(length=100), nullable=True),
    sa.Column('out_of_town', sa.Boolean(), nullable=True),
    sa.Column('import_updates_enabled', sa.Boolean(), nullable=True),
    sa.Column('import_deletes_enabled', sa.Boolean(), nullable=True),
    sa.Column('breed_primary', sa.String(length=255), nullable=False),
    sa.Column('breed_secondary', sa.String(length=255), nullable=True),
    sa.Column('is_mixed', sa.Boolean(), nullable=False),
    sa.Column('age_category', sa.String(length=20), nullable=False),
    sa.Column('age_years_approx', sa.Float(), nullable=True),
    sa.Column('age_label', sa.String(length=50), nullable=True),
    sa.Column('age_range_label', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('weight_min', sa.Float(), nullable=True),
    sa.Column('weight_max', sa.Float(), nullable=True),
    sa.Column('weight_range_label', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('color_secondary', sa.String(length=100), nullable=True),
    sa.Column('color_tertiary', sa.String(length=100), nullable=True),
    sa.Column('coat_length', sa.String(length=50), nullable=True),
    sa.Column('declawed', sa.Boolean(), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('spayed_neutered', sa.Boolean(), nullable=True),
    sa.Column('vaccinated', sa.Boolean(), nullable=True),
    sa.Column('special_needs', sa.Boolean(), nullable=False),
    sa.Column('special_needs_notes', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('house_trained', sa.Boolean(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('requires_fenced_yard', sa.Boolean(), nullable=True),
    sa.Column('knows_basic_commands', sa.Boolean(), nullable=True),
    sa.Column('behavior_other_animals', sa.Text(), nullable=True),
    sa.Column('good_with_kids', sa.Boolean(), nullable=True),
    sa.Column('good_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('good_with_cats', sa.Boolean(), nullable=True),
    sa.Column('good_with_other_animals', sa.Boolean(), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('location_contact_name', sa.String(length=255), nullable=True),
    sa.Column('location_email', sa.String(length=255), nullable=True),
    sa.Column('location_phone', sa.String(length=50), nullable=True),
    sa.Column('is_appt_only', sa.Boolean(), nullable=True),
    sa.Column('is_map_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_public_location', sa.Boolean(), nullable=True),
    sa.Column('private_address', sa.Boolean(), nullable=True),
    sa.Column('location_street', sa.Text(), nullable=True),
    sa.Column('location_street2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('shelter_name', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('org_type', sa.String(length=100), nullable=True),
    sa.Column('org_custom_url_alias', sa.String(length=255), nullable=True),
    sa.Column('org_website', sa.Text(), nullable=True),
    sa.Column('org_social_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('org_mission_statement', sa.Text(), nullable=True),
    sa.Column('org_onsite_vet', sa.Boolean(), nullable=True),
    sa.Column('org_supports_rehome', sa.Boolean(), nullable=True),
    sa.Column('org_spay_neuter_policy', sa.Text(), nullable=True),
    sa.Column('org_special_services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('org_adoption_url', sa.Text(), nullable=True),
    sa.Column('org_adoption_fee_min', sa.Float(), nullable=True),
    sa.Column('org_adoption_fee_max', sa.Float(), nullable=True),
    sa.Column('org_annual_adoptions', sa.Float(), nullable=True),
    sa.Column('org_annual_intake', sa.Float(), nullable=True),
    sa.Column('org_foster_count', sa.Float(), nullable=True),
    sa.Column('org_employee_count', sa.Float(), nullable=True),
    sa.Column('org_volunteer_count', sa.Float(), nullable=True),
    sa.Column('org_display_id', sa.String(length=50), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_first_name', sa.String(length=255), nullable=True),
    sa.Column('contact_last_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media_records', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('petfinder_notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('petfinder_url', sa.Text(), nullable=True),
    sa.Column('sponsor_a_pet_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('adoption_fee', sa.Float(), nullable=True),
    sa.Column('adoption_fee_waived', sa.Boolean(), nullable=True),
    sa.Column('display_adoption_fee', sa.Boolean(), nullable=True),
    sa.Column('adoption_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adoption_status_change_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intake_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intake_type', sa.String(length=50), nullable=True),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_from_org_id', sa.String(length=36), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_source_id')
    )
    op.create_table('raw_scrapes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_scrapes_source_id', 'raw_scrapes', ['source', 'source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_scrapes_source_id', table_name='raw_scrapes')
    op.drop_table('raw_scrapes')
    op.drop_table('dog_profiles')
    op.drop_index('ix_dog_profile_history_profile_id', table_name='dog_profile_history')
    op.drop_table('dog_profile_history')
    # ### end Alembic commands ###
